### ISSUE TITLE
Execution never ends

### ISSUE THREAD

**Issue by pcav** [havatv/qgisthingreyscaleplugin#2]
It stops at 50%, qgis.bin taking 99% of the CPU.
If clicked on cancel, it stops.

**Comment by havatv** [comment]
As written in the documentation, the plugin will take a lot of time to finish if a high percentage of the pixels have higher pixel values than the level values (the more massive, the more iterations).  It is most useful for "sparse" images (I developed for trajectory data).
The progress bar is not very realistic, as it just "counts" the levels.  The highest levels will take much less time than the lower levels.  It is very difficult to predict how many iterations that will be necessary for each level, so a realistic progress bar is difficult to achieve.
Do you have any suggestions for how to improve this?

**Comment by pcav** [comment]
Perhaps better to rerun the progress bar for each iteration?

**Comment by havatv** [comment]
I have considered that, but the user will not know how many iterations there will be...
But perhaps it is useful just to let the user know that something is going on.

**Comment by havatv** [comment]
I have tried to add a second progressbar to show activity during iterations.  I will upload a new version of the plugin to the repository.

**Comment by havatv** [comment]
I close the issue.  Please reopen if more needs to be done.

**Comment by pcav** [comment]
Agreed, thanks.
